/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_asdev_libqexec_QExec */

#ifndef _Included_com_asdev_libqexec_QExec
#define _Included_com_asdev_libqexec_QExec
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_asdev_libqexec_QExec
 * Method:    exec0
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_asdev_libqexec_QExec_exec0
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_asdev_libqexec_QExec
 * Method:    execToConsole
 * Signature: (Ljava/lang/int;)V
 */
JNIEXPORT jint JNICALL Java_com_asdev_libqexec_QExec_execToConsole
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
